### ISSUE TITLE
Cython extensions make for slow builds.

### ISSUE THREAD

**Issue by shawnsarwar** [pluralsight/spavro#6]
This is just a small quality of life improvement. Would it be possible to package binaries for common architectures with spavro? We use spavro in a number of containers which are constantly being built fresh for testing. The extension compilation from source adds up to a non-trivial amount of time.

**Comment by mikepk** [comment]
Hey @shawnsarwar. Unfortunately building binary packages for all the possible linux distros + python versions + common CPU architectures is not trivial and not something I really have the time for ATM. I started to look into it but even with some of the newer tooling it's still pretty complicated.

However there is a way where you can improve your life significantly without it being in the library itself (and is generally a good practice anyway). You can build python wheels for the library (and all your requirements) and then have your deploy use the pre-compiled wheel. That should speed up your deploy significantly by doing the compile step once, creating a deploy artifact for the library and then just copying that to your targets. Also if the library doesn't change you don't need to recompile the wheel, so that's another win. You do have to compile on a system that matches your target (ideally the same python version, same linux distro, etc...) but it's usually something you can put into a CI/CD pipeline.

Make sure you have relatively recent pip, and make sure you have the `wheel` package as well (`pip install wheel`). If you want to play with this you can do something like:

`pip wheel --wheel-dir /tmp/wheels -r requirements.txt`

then when you deploy copy the wheel dir to your target hosts and you can do something like:

`pip install --no-index --find-links=/tmp/wheels -r requirements.txt`

You can also do the same with individual packages if you want.
