### ISSUE TITLE
Logical Types

### ISSUE THREAD

**Issue by JohnEmhoff** [pluralsight/spavro#8]
Does spavro support logical types? As far as I can tell the logicalType field is ignored and an error is thrown if (e.g.) a datetime object is used instead of an int or whatever.

**Comment by JohnEmhoff** [comment]
Sorry, here's an example of something I would expect to work: https://gist.github.com/JohnEmhoff/d92c456376738cbf3160ceff3b992b50

It throws an exception along the lines of:
```
<cyfunction make_record_writer.<locals>.write_record at 0x7f94c89216c0>
type error
Traceback (most recent call last):
  File "src/spavro/fast_binary.pyx", line 578, in spavro.fast_binary.make_record_writer.write_record
  File "src/spavro/fast_binary.pyx", line 641, in spavro.fast_binary.make_int_writer.checked_int_write
TypeError: Schema violation, 2010-01-01 is not an example of schema {'type': 'int', 'logicalType': 'date'}
```

**Comment by mikepk** [comment]
So the idea behind a logical type is that it's actually just an extra attribute that lets clients do "smart" things with the underlying data. Logical types are _always_ stored as their underlying "primitive" type (in this case Int). That's why trying to save a datetime object is throwing an error, the datetime object is not an integer.

You can read more in the Avro spec: https://avro.apache.org/docs/current/spec.html#Logical+Types

but the key phrase is this one: 

> A logical type is **always serialized using its underlying Avro type** so that values are encoded in exactly the same way as the equivalent Avro type that does not have a logicalType attribute. Language implementations may choose to represent logical types with an appropriate native type, although this is not required.

So how would you use this? The idea would be to find a way to store your datetime as an integer, maybe like this:
```python
dt = datetime.datetime.utcnow()
# turn the datetime into an integer
datetime_integer = int(dt.timestamp() * 1000)
```
You're storing an integer but it has more "meaning" in that it's actually a timestamp. Remember you can also choose which primitive type is the underlying storage, so you could have used a float as the type in the above example and saved more precision.

The schema attribute is optional and just tells your code that when you're reading it you can convert the integer back into a datetime (if you wish). You might do something like this to convert the int back in your case:
```python
# value is an integer
stored_item = read_data_from_avro()
value = stored_item["d"]
dt = datetime.datetime.fromtimestamp(value / 1000)
```

If you think about it, it has to be this way since Avro is cross language / cross environment. What would Java do with a python datetime object? What would any compatible reader do if it couldn't handle the data type (didn't know what it was).

That's why it's always stored as the primitive type so that _any_ client that implements Avro can read the data, even if they might not have the additional contextual knowledge of how to use the data, they still have the data.

Make sense?

**Comment by mikepk** [comment]
Also, although the spec doesn't specifically say this, I believe it's OK to add custom LogicalTypes since the way they're defined, any implementation that doesn't understand the type just ignores it (and uses the underlying primitive type). 

I've found it to be best practice to actually namespace the logical type so that it's clear that it's a custom type. For example you might call your logical type something like "ehmoffapplication.timestamp". That way your application knows what to do with it, but it won't get confused with the other ones defined in the spec.

The spec defines a small set of LogicalTypes and their meaning, so you would want to avoid colliding with them if possible.

**Comment by JohnEmhoff** [comment]
Thanks for the detailed response -- it all makes sense and is in line with my understanding of avro.

I think where our expectations differ is that it seems perfectly reasonable to me for a specific implementation to do this conversion to and from the "native" types. I'm pretty sure the apache implementation does this?

Alternatively, some hooks into the library to provide custom converters for logical types would work too. I know it's not too hard to write this code myself and operate on the data spavro returns, but I figured I'd ask because a) this is code that is going to be written be pretty much any user of spavro and b) I imagine it'd be more efficient for spavro to do it at read time, rather than this general purpose, recursive type walker

**Comment by mikepk** [comment]
I believe you're correct, the base Apache version does in fact handle the 8 default logical types automatically. Spavro was written to be focused on encoding/decoding speed and so a lot of work went into the primitive storage part and less on the API layer (since it's intended to keep the Apache API). 

The parse-once schema handling is also one of the reasons spavro is so fast (compared to other implementations) so I'd have to look at whether adding the default logical type handling would impact that.

In the environment where spavro was mainly used, the handling in application code was preferred but I see your point on there being an expectation since this is a python implementation. Also, it does violate the intention of spavro being a drop-in replacement for the Apache implementation. Things to noodle on, thank you.

**Comment by mikepk** [comment]
Interestingly, I think Apache only recently added the python code for LogicalTypes (as in June of 2019 https://github.com/apache/avro/pull/545) which is why it wasn't present in my original fork (from 2017).

**Comment by JohnEmhoff** [comment]
Sounds good all around, thanks for the background! We'll do this in application-space. And thanks for spavro, it's been pretty nice to work with.

**Comment by tenth10th** [comment]
(Resolved as "will fix in application-space" )
